### PR TITLE
Update sed commands in entrypoint.sh to match datadog.conf patterns.

### PR DESCRIPTION
**Pull request by hkaj**

### CODE REVIEW

**Comment by hkaj** [comment]
updated it to include the alpine image

**Comment by degemer** [comment]
👍

**Comment by fotinakis** [comment]
@hkaj @degemer, this change broke TAGS environment handling in the latest `datadog/docker-dd-agent` image — my datadog agent is no longer reporting data with any tags associated.

Previously my `/etc/dd-agent/datadog.conf` would contain the correct tags, but now it contains the incorrect defaults:
```
# Set the host's tags
#tags: mytag, env:prod, role:database
```

**Comment by hkaj** [comment]
Hi @fotinakis 
Thanks for reporting this, #116 fixed it. Let me know if any issue remains.

**Pull request merged**
