### PR TITLE
supporting env vars in yaml files under /etc/dd-agent/conf.d

### PR DESCRIPTION
**Pull request by shayts7**
Hi,

A code to run over all of the yaml conf files and replace any env var with it related value.
I actually copy paste most of the code but I tested it locally and it looks fine.

There is also the option to use `envsubst`, but it was not installed on the image, so I choose to implement it with regex.

Thanks,
Shay

### CODE REVIEW

**Comment by hkaj** [comment]
Hi @shayts7, thanks for contributing!
May I ask what your use case is? If the config you want to auto-fill will be used to monitor stuff running in containers we're actually building a service discovery feature that should help. It's still in beta right now but will go out with `5.8` (so in a matter of weeks) and we provide images that embed it using the tags `sd-beta` and `sd-kubernetes-beta` (depending on if you run them in kubernetes or not) instead of `latest` as well as some documentation here: https://github.com/DataDog/dd-agent/wiki/Service-discovery

Let me know if that helps.

**Comment by shayts7** [comment]
Hi @hkaj, 

I wanted to monitor etcd, but I wanted to do it like any other application (running in containers) in the host does.
our applications access etcd using the local host ip, so I wanted to push the host ip into datadog configuration. The way I choose doing it is using capability of replacing ENV VARs when datadog agent start running, using this capability the only thing I had to do is to pass the host ip as env var to datadog agent docker container.

**Comment by shayts7** [comment]
I have few questions about the service discovery feature:

From the doc: "if no template is found in the user-supplied configuration store, the Agent will try to match the container image with a list of auto-configurable checks (the simplest ones, mostly)" - do you have a list of the auto-configurable checks?

If for instance I want datadog to monitor my container - is there any protocol I need to applied in my REST API layer? (for instance: I can expose /system-health REST endpoint and configure datadog to monitor it. The question is - what is the payload that my endpoint should return to datadog?)

As for security - assume that my service blocks any API call for non-authorized clients (let's say my service support oauth), how would you recommend to configure the authentication tokens in datadog's service discovery configuration? 

What would you recommend me to do if I already have service discovery for my services? (we use DNS round robin using registrator and skydns)
In that case I see advantage for what you suggest and that is that I can be sure that any container in my cluster will be monitored. Using our service discovery only the service as a whole will be monitor but I cannot guarantee that any container composing the service will be monitored.

Thanks,
Shay

**Comment by hkaj** [comment]
Hi @shayts7 

> do you have a list of the auto-configurable checks?

here is the list of auto-configurable checks and the config options they will have: https://github.com/DataDog/dd-agent/tree/haissam/service-discovery/conf.d/auto_conf

> If for instance I want datadog to monitor my container - is there any protocol I need to applied in my REST API layer?

The service discovery feature is actually very simple. It queries the docker daemon API for running containers, compares their images to images for which it has a configuration template (either user-provided - through a configuration store, or embedded in the agent: the `auto-conf` directory I mention above) and enable agent checks based on these templates.

So if you want the agent to report custom metrics coming from your own containerized app you will need to write your own custom check that can collect these stats from your container (a health API endpoint is indeed a good way to expose this data) and add a config template that enables that check for your custom image in the config store.

Documentation about writing a custom check is available [here](http://docs.datadoghq.com/guides/agent_checks/).

Though before writing a custom check I'd advise looking at existing ones that might meet your needs.
For example the http check may well be enough depending on your use case. If you use java services, the JMX integration could also help, etc.

> how would you recommend to configure the authentication tokens in datadog's service discovery configuration?

The current (beta) version of service discovery doesn't provide any additional security layer. Auth tokens, and credentials in general need to be stored in the configuration template (so in etcd or consul). For the next iteration we're considering more secure ways to store these. 

> What would you recommend me to do if I already have service discovery for my services?

The way service discovery is done in the datadog agent is independent of any other service discovery mechanism you might be using already. It considers docker containers individually and only cares about the image it's running, not the service it's part of. Enabling service discovery for the agent will not change how your other service discovery mechanism works.

My recommendation would be to add the service as a docker label to your containers if possible, this way the agent can pick it up, and add it as a tag which will be valuable when you will want to visualize your infrastructure or graph metrics per service.

Let me know if you have any other question.

**Comment by shayts7** [comment]
Thanks for the detailed info!

**Comment by hkaj** [comment]
closing as this is likely fixed by [service discovery](http://docs.datadoghq.com/guides/servicediscovery/).
Feel free to reach out if not.

**Pull request closed without merging**
