### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thedug**
Commands are missing --privileged

### CODE REVIEW

**Comment by LeoCavaille** [comment]
@LotharSee is the `--privileged` flag mandatory for every use case?

**Comment by alq666** [comment]
Should not be.

**Comment by thedug** [comment]
If not then why does the comment above tell you not to forget it?

**Comment by LotharSee** [comment]
Should no longer be a requirement with latest version of Docker. Will double-check it on multiple system then update the README accordingly.

**Comment by remh** [comment]
It's not needed anymore. Closing.

**Comment by korya** [comment]
Your documentation stills suggests using the `--privileged` flag:
- https://app.datadoghq.com/account/settings#agent/coreos
- https://app.datadoghq.com/account/settings#agent/docker

**Comment by LotharSee** [comment]
Hi @korya,

So technically, it depends on the security parameters of the system (it is required on CentOS, Fedora, and RHEL).
We are in the middle of a revamp of our Docker integration. The next version will be much clearer about it.

**Pull request closed without merging**
