### PR TITLE
Support arm64v8

### PR DESCRIPTION
**Pull request by toshitanian**
### What does this PR do?
Added Dockerfile for armv8, based on one for alpine

### Motivation
We're gonna run docker-agent on ARM devices. It's good if we can contribute to community and improve ecosystems.

### Testing Guidelines
Let me know if there's any guideline for testing Dockerfile.

### Additional Notes
- we're gonna add other Dockerfiles, for armv7.

### CODE REVIEW

**Comment by hkaj** [comment]
Hi @toshitanian 
Thanks for the PR! I'll try and test it shortly. FYI we have a new agent on the way: https://github.com/DataDog/datadog-agent and its docker images are in the same repo: https://github.com/DataDog/datadog-agent/tree/6.0.0-beta.1/Dockerfiles

The current `docker-dd-agent` repository will keep receiving bugfixes but all new development happens in the new repo.

What I'm saying is we'll gladly accept your PR for this agent, but if you want the image to be maintained in the long run, https://github.com/DataDog/datadog-agent/tree/6.0.0-beta.1/Dockerfiles is the place to be.

We will consider adding an arm-based image ourselves some time in the future if you don't have time for this now or find that the paint in this new repo is still too fresh.

**Comment by toshitanian** [comment]
Hi @hkaj 

Thank you for your reply. 

I got that you are not developing new features in v5.
Is it possible for you to release docker image built from this Dockerfile to your dockerhub repo as like `datadog/docker-dd-agent:latest-arm64v8` ? If not, we will host it on our repo.

I heard about agent v6 written w/ Go, and have questions about the version.
I asked about release plan to datadog's support team. They answered that there're too much thing to do before releasing v6 and working version is not available. When are you planning to release v6 publicly?

And of course, we can contribute to v6 with arm images.

**Comment by irabinovitch** [comment]
@toshitanian  We are targeting official ARM support in Agent 6.x later this year.  Happy to add your contact information on that feature request so we can loop you in when its ready.

In the mean time I'd like to close this PR since development on 5.x has slowed down.  

CC: @mikezvi @dsahni

**Comment by toshitanian** [comment]
Thanks. It's not hurry for now. I will close this PR.

**Pull request closed without merging**
