### PR TITLE
Enable k8s event collection based on a namspace name regex

### PR DESCRIPTION
**Pull request by alexouzounis**
### What does this PR do?

Enables the Kubernetes Namespace name Regex for event collection in the docker image via environment variables

### Motivation

Make easier to use the DDAgent image for Kubernetes

### Additional Notes

To be merged after ~5.11 is released; https://github.com/DataDog/dd-agent/milestone/76~ 5.12 is released, https://github.com/DataDog/dd-agent/milestone/79

### CODE REVIEW

**Comment by alexouzounis** [comment]
@hkaj Any chance this can get merged ?

**Comment by hkaj** [comment]
@alexouzounis we actually moved the linked dd-agent change to 5.12. Basically the 5.11 milestone was renamed 5.12 and we used 5.11 to release only the trace agent (our new APM product).

**Comment by alexouzounis** [comment]
ah damn ok, will update the description, thanks.

**Comment by alexouzounis** [comment]
Hey @hkaj ! Milestone 5.12 appears completed - could you merge this ?

**Comment by hkaj** [comment]
Yep! Thanks @alexouzounis

**Comment by alexouzounis** [comment]
sweet thanks

**Pull request merged**
